//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyCinema
{
    using System;
    using System.Collections.Generic;
    
    public partial class Movy
    {
        public int Id { get; set; }
        public string movie_name { get; set; }
        public string movie_dis { get; set; }
        public string movie_date { get; set; }
        public string movie_time { get; set; }
        public string movie_pic { get; set; }
        public string movie_hall { get; set; }
        public double price { get; set; }
        public string Category { get; set; }
        public string Age_limit { get; set; }
        public double Discount { get; set; }
    }
}
