//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyCinema.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BookSeat
    {
        public int Id { get; set; }
        public string movieName { get; set; }
        public string moviedate { get; set; }
        public string movietime { get; set; }
        public string seatno { get; set; }
        public string Full_Name { get; set; }
        public string movieId { get; set; }
    }
}
